### ISSUE TITLE
Bug in `set_indexing_prop!` following `add_vertex!`

### ISSUE THREAD

**Issue by sbromberger** [sbromberger/MetaGraphs.jl#32]
MWE:
```
julia> mg = MetaGraph(DiGraph())
{0, 0} undirected Int64 metagraph with Float64 weights defined by :weight (default weight 1.0)

julia> add_vertex!(mg)
true

julia> set_indexing_prop!(mg, 1, :a, 10)
Set(Symbol[:a])

julia> props(mg, 1)
Dict{Symbol,Any} with 1 entry:
  :a => 10

julia> mg.metaindex
Dict{Symbol,Dict{Any,Integer}} with 1 entry:
  :a => Dict{Any,Integer}(Pair{Any,Integer}(10, 1))

julia> add_vertex!(mg)
true

julia> set_indexing_prop!(mg, 2, :a, 20)
ERROR: KeyError: key 2 not found
Stacktrace:
 [1] getindex at ./dict.jl:474 [inlined]
 [2] set_indexing_prop!(::MetaGraphs.MetaGraph{Int64,Float64}, ::Int64, ::Symbol, ::Int64) at /Users/seth/.julia/v0.6/MetaGraphs/src/MetaGraphs.jl:361
```

It seems that the `delete!` call on L361 is the problem.

@kescobo - do you have a few minutes to chase this down?

**Comment by kescobo** [comment]
If it's relatively quick (1 hour or so), then yes. At minimum I can find the problem and report what it is, if not take the time to fix it.

**Comment by kescobo** [comment]
I'm sorry - I haven't had a moment to look at this. On it this week though.

**Comment by kescobo** [comment]
Clearly my last claim was a lie :-(

It's still my intention to work on this, but my intentions around development are consistently being forced to a back seat to my other work. Sorry :-(

**Comment by skleinbo** [comment]
I thought the issue was not too hard to fix. Hope you don't mind me opening a PR. Do you think it'd be more appropriate if one could call `set_prop!` on an indexed attribute, which would update the index automatically? Now one has to call `set_indexing_prop!` on indexed attributes and `set_prop!` on non-indexed ones. Feels a bit artificial.

**Comment by sbromberger** [comment]
@skleinbo - I think that calling `set_indexing_prop!` to set the name of the index should stay, but I like the idea of using `set_prop!` once the indexing property has been set. It seems more consistent.

**Comment by skleinbo** [comment]
@sbromberger Agreed. I'll try to implement it and open another PR.

**Comment by sbromberger** [comment]
@skleinbo awesome. Not to rush, but I'm really eager to tag a new version :)

**Comment by kescobo** [comment]
Thanks for taking care of that! It's been hanging over my head for months 😬  - glad it was a straightforward fix

**Comment by skleinbo** [comment]
Embarrassingly, I managed to produce an error in three lines of code :( See https://github.com/JuliaGraphs/MetaGraphs.jl/pull/44#discussion_r211541593

The unit tests didn't capture it, because the line was triggered only when calling `set_indexing_prop!` on a non-existing `prop`. Fixed and adapted tests in recent PR.

Sorry for the hassle.
